In [1]:
import numpy as np

In [2]:
# как создать матрицу?

In [3]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [4]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# размер матрицы
np.shape(A)

(4, 3)

In [6]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [7]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [8]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [9]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [10]:
# создание специальных матриц

In [11]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [16]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [17]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [18]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [19]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [20]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [21]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [22]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [23]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [24]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [25]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [26]:
x_col.T

array([[1, 2, 3]])

In [27]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [28]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [42]:
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])

In [43]:
inc = inc.T
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [36]:
cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
cons = cons.T
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [44]:
inc_clear = inc*0.87
inc_clear

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [45]:
inc_clear - cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [46]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [47]:
A

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

In [48]:
np.dot(A,x)

array([26, 30])

In [49]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
print(A)
print(B)

[[1 9 8 5]
 [3 6 3 2]
 [3 3 3 3]
 [0 2 5 9]
 [4 4 1 2]]
[[ 1 -1  0  1  1]
 [-2  0  2 -1  1]]


In [50]:
np.dot(B, A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [51]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [54]:
A = np.array([x, y, z])
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [55]:
np.dot(A, A.T)

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [56]:
np.dot(A.T, A)

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [90]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [58]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [59]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [89]:
Count_DF = Count_DF.values
Price_DF = Price_DF.values


AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [79]:
Price_DF

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [85]:
price_s

array([1.18, 1.36, 1.05, 1.72, 2.05, 3.35, 1.09, 2.75])

In [80]:
price_s = np.dot(Price_DF, com)
itog_s = price_s@Count_DF
itog_s

array([123.03, 123.21, 200.86, 327.98, 208.66])

In [73]:
prib = np.dot(Count_DF,Price_DF.T)
prib

array([[ 61.5,  67.5,  57.5,  89.6,  96.5, 166. ,  58.5, 130. ],
       [ 64.5,  90.1,  70.5,  69.2, 118.5, 189. ,  50.4, 137.5],
       [ 70. ,  85.6,  71. ,  68. , 108. , 190. ,  47. , 140. ],
       [ 54.2,  64.2,  41. ,  88.4,  95.5, 154.5,  54.9, 119. ],
       [114.5, 143.3, 110.5, 172.4, 208.5, 331. , 115.2, 255.5],
       [ 52.1,  56.5,  58.5,  64.8,  74.5, 135. ,  45.9, 103. ],
       [ 89.5,  91.1,  98.5, 112. , 121.5, 227. ,  77.7, 178. ],
       [ 97.8, 102.6,  85.5, 180.2, 152.5, 260. , 117.3, 196. ]])

In [84]:
com_d = np.diag(com)
com_d

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.3, 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0.1]])

In [86]:
Price_DF

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [87]:
price_s2 = Price_DF@com_d
price_s2

array([[0.4 , 0.3 , 0.3 , 0.08, 0.1 ],
       [0.36, 0.5 , 0.3 , 0.1 , 0.1 ],
       [0.4 , 0.4 , 0.  , 0.05, 0.2 ],
       [0.36, 0.24, 0.84, 0.08, 0.2 ],
       [0.5 , 0.7 , 0.6 , 0.1 , 0.15],
       [1.  , 1.  , 0.9 , 0.2 , 0.25],
       [0.22, 0.2 , 0.45, 0.05, 0.17],
       [0.9 , 0.8 , 0.75, 0.1 , 0.2 ]])

In [91]:
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [92]:
nesalon_inc = (P*C)@(np.ones(5)-com)
print(nesalon_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [94]:
A  =np.matrix('1,2;2,5')
A

matrix([[1, 2],
        [2, 5]])

In [95]:
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [96]:
A = np.matrix('2,0,0;0,1,0;0,0,4')
A

matrix([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 4]])

In [99]:
A_inv = np.linalg.inv(A)
A_inv

matrix([[0.5 , 0.  , 0.  ],
        [0.  , 1.  , 0.  ],
        [0.  , 0.  , 0.25]])

In [100]:
0.5*0.25

0.125

In [1]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

# загружаем датасет
boston = datasets.load_boston()
boston_data = pd.DataFrame(
    data=boston.data, #данные
    columns=boston.feature_names #наименования столбцов
)
boston_data['PRICE'] = boston.target
boston_data.head()

c:\Users\Asya\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [2]:
# составляем матрицу А и вектор целевой переменной
CRIM = boston_data['CRIM']
RM = boston_data['RM']
A = np.column_stack((np.ones(506), CRIM, RM))
y = boston_data[['PRICE']]
print(A)

[[1.0000e+00 6.3200e-03 6.5750e+00]
 [1.0000e+00 2.7310e-02 6.4210e+00]
 [1.0000e+00 2.7290e-02 7.1850e+00]
 ...
 [1.0000e+00 6.0760e-02 6.9760e+00]
 [1.0000e+00 1.0959e-01 6.7940e+00]
 [1.0000e+00 4.7410e-02 6.0300e+00]]


In [5]:
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]


In [6]:
# добавились новые данные:
CRIM_new = 0.1
RM_new = 8
# делаем прогноз типичной стоимости дома
PRICE_new = w_hat.iloc[0]+w_hat.iloc[1]*CRIM_new+w_hat.iloc[2]*RM_new
print(PRICE_new.values)

[37.85733519]


In [7]:
# короткий способ сделать прогноз
new=np.array([[1,CRIM_new,RM_new]])
print('prediction:', (new@w_hat).values)

prediction: [[37.85733519]]


In [8]:
from sklearn.linear_model import LinearRegression
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
new_prediction = model.predict(new)
print('prediction:', new_prediction)

w_hat: [[-29.24471945  -0.26491325   8.39106825]]
prediction: [[37.85733519]]


In [11]:
A = np.array([-0.535, -0.267, 0.802])
B = np.array([0.707, -0.707, 0])

np.dot(A.T, B)

-0.189476

In [12]:
np.dot(A.T, A)

1.000718

In [16]:
A

CHAS  LSTAT     CRIM     RM
0     0.0   4.98  0.00632  6.575
1     0.0   9.14  0.02731  6.421
2     0.0   4.03  0.02729  7.185
3     0.0   2.94  0.03237  6.998
4     0.0   5.33  0.06905  7.147
..    ...    ...      ...    ...
501   0.0   9.67  0.06263  6.593
502   0.0   9.08  0.04527  6.120
503   0.0   5.64  0.06076  6.976
504   0.0   6.48  0.10959  6.794
505   0.0   7.88  0.04741  6.030

[506 rows x 4 columns]

In [17]:
A_cent

CHAS     LSTAT      CRIM        RM
0   -0.06917 -7.673063 -3.607204  0.290366
1   -0.06917 -3.513063 -3.586214  0.136366
2   -0.06917 -8.623063 -3.586234  0.900366
3   -0.06917 -9.713063 -3.581154  0.713366
4   -0.06917 -7.323063 -3.544474  0.862366
..       ...       ...       ...       ...
501 -0.06917 -2.983063 -3.550894  0.308366
502 -0.06917 -3.573063 -3.568254 -0.164634
503 -0.06917 -7.013063 -3.552764  0.691366
504 -0.06917 -6.173063 -3.503934  0.509366
505 -0.06917 -4.773063 -3.566114 -0.254634

[506 rows x 4 columns]

In [13]:
# составляем матрицу наблюдений без дополнительного столбца из единиц
A = boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]
y = boston_data[['PRICE']]
# стандартизируем векторы в столбцах матрицы A
A_cent = A - A.mean()
A_st = A_cent/np.linalg.norm(A_cent, axis=0)
A_st.describe().round(2)

CHAS   LSTAT    CRIM      RM
count  506.00  506.00  506.00  506.00
mean    -0.00   -0.00    0.00   -0.00
std      0.04    0.04    0.04    0.04
min     -0.01   -0.07   -0.02   -0.17
25%     -0.01   -0.04   -0.02   -0.03
50%     -0.01   -0.01   -0.02   -0.00
75%     -0.01    0.03    0.00    0.02
max      0.16    0.16    0.44    0.16

In [19]:
10.4+8+2+3+0.4*16

29.799999999999997

In [40]:
A = np.array([[1, 3, -2, 9],[1, 9, 4, 81]]).T
y = np.array([3, 7, -5, 21])

In [41]:
A

array([[ 1,  1],
       [ 3,  9],
       [-2,  4],
       [ 9, 81]])

In [30]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree = 2, include_bias = True)

In [42]:
A_poly = poly.fit_transform(A)
A_poly

array([[ 1.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,
         1.000e+00],
       [ 1.000e+00,  3.000e+00,  9.000e+00,  9.000e+00,  2.700e+01,
         8.100e+01],
       [ 1.000e+00, -2.000e+00,  4.000e+00,  4.000e+00, -8.000e+00,
         1.600e+01],
       [ 1.000e+00,  9.000e+00,  8.100e+01,  8.100e+01,  7.290e+02,
         6.561e+03]])

In [43]:
w_mnk = np.linalg.inv(A_poly.T@A_poly)@A_poly.T@y
w_mnk

LinAlgError: Singular matrix

In [28]:
y.shape

(506, 1)

In [44]:
A = np.array([
    [1, 1, 1], 
    [1, 3, 9],
    [1, -2, 4], 
    [1, 9, 81]
])
np.linalg.matrix_rank(A)

3

In [45]:
A_T_A = A.T@A
A_T_A

array([[   4,   11,   95],
       [  11,   95,  749],
       [  95,  749, 6659]])

In [46]:
np.linalg.det(A_T_A)

188711.99999999985

In [47]:
A_1 = np.linalg.inv(A_T_A)
A_1

array([[ 0.37943533, -0.01109627, -0.00416508],
       [-0.01109627,  0.0933221 , -0.01033851],
       [-0.00416508, -0.01033851,  0.00137246]])

In [49]:
w_mnk2 = A_1@A.T@y
w_mnk2

array([ 0.11446013,  2.46095638, -0.01608801])

In [48]:
w_mnk = np.linalg.inv(A.T@A)@A.T@y
w_mnk

array([ 0.11446013,  2.46095638, -0.01608801])

In [50]:
from sklearn.model_selection import cross_validate

In [57]:
# выделяем интересующие нас факторы
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]
 
# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=2, include_bias=False)
X = poly.fit_transform(X)
 
# создаём модель линейной регрессии
lr = LinearRegression()
 
# оцениваем качество модели на кросс-валидации, метрика — MAPE
cv_results = cross_validate(lr, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100))	

MAPE на тренировочных фолдах: 13.47 %
MAPE на валидационных фолдах: 17.34 %


In [64]:
x1 = np.array([5,9,4,3,5])
x2 = np.array([15,18,18,19,19])
x3 = np.array([7,6,7,7,7])
y = np.array([24,22,35,33,36])
a = 1

In [62]:
X = np.array([[1,1,1,1,1],x1, x2, x3]).T
X

array([[ 1,  5, 15,  7],
       [ 1,  9, 18,  6],
       [ 1,  4, 18,  7],
       [ 1,  3, 19,  7],
       [ 1,  5, 19,  7]])

In [68]:
X.shape

(5, 4)

In [71]:
X.T@X

array([[   5,   26,   89,   34],
       [  26,  156,  461,  173],
       [  89,  461, 1595,  605],
       [  34,  173,  605,  232]])

In [70]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
w_ridge = np.linalg.inv(X.T@X+a*np.eye(4))@X.T@y
np.around(w_ridge, 2)

array([-0.09, -1.71,  1.91,  0.73])

In [75]:
7*8

56

In [78]:
A = np.array([
    [1, 9, 4], 
    [9, 4, 7], 
    [4, 7, 12]
])

G = A.T@A

eig_values, eig_vectors = np.linalg.eig(G)
np.round(eig_values)

array([391.,  46.,  16.])

In [79]:
np.round(eig_vectors.T@eig_vectors)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0., -0.,  1.]])

In [80]:
4-4*0.36

2.56

In [81]:
4*36-400

-256

In [82]:
400-4*36

256

In [85]:
256**(1/2)

16.0

In [88]:
C

array([list([1, 0, 9922]), list([0.9922, 1])], dtype=object)

In [105]:
C = np.array([
    [1, 0.9922], 
    [0.9922, 1]
])

eig_values, eig_vectors = np.linalg.eig(C)
sobs = eig_vectors[0]


In [103]:
X2 = np.array([70, 130, 65, 60])-81.25
n = np.linalg.norm(X2)
X2 = X2/n
X2

array([-0.19829369,  0.85927267, -0.28642422, -0.37455475])

In [101]:
(70+130+65+60)/4

81.25

In [99]:
X1 = np.array([-0.25, 0.75, -0.25, -0.25])/0.866

In [100]:
X1

array([-0.2886836 ,  0.86605081, -0.2886836 , -0.2886836 ])

In [106]:
newfactor = sobs[0]*X1 + sobs[1]*X2
newfactor

array([-0.06391532,  0.00479287, -0.00159762,  0.06072007])

In [108]:
newfactor_st = newfactor/np.linalg.norm(newfactor)
np.round(newfactor_st, 4)

array([-0.7238,  0.0543, -0.0181,  0.6876])

In [113]:
prog={'bennet@xyz.com', 'darcy@abc.com', 'margaret@xyz.com', 'pa@hhh.com', 'marimari@xyz.com', 'mallika@yahoo.com', 'abc@xyz.com', '0071235@gmail.ru'}
ml={'marimari@xyz.com','darcy@abc.com','0071235@gmail.ru','darcy@abc.com','petr44@xyz.com','katrin@ya.com'}

In [114]:
union = prog.union(ml)
len(union)

10

In [115]:
intercept = prog.intersection(ml)
len(intercept)

3

In [116]:
s_d = prog.symmetric_difference(ml)
len(s_d)

7